name: Build and deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - package.json
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Node.js 14.x
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Dependency cache. (Yarn cache and node_modules)
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn Chche
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # If the dependency cache was hit, this step should take 0s to run.
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: yarn prettier:check

      - name: Run ESLint
        run: yarn eslint:check

      - name: Run Markdown Lint
        run: yarn mdlint:check

      - name: Build
        run: yarn pages:build

      # Compress /dist in a gzipped tarball, can increase the upload speed.
      - name: Package
        run: cd ./pages/.vuepress/dist && tar -czvf dist.tar.gz *

      # Removing, uploading, unzipping and removing again.
      - name: Deploy
        uses: mdallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: "./pages/.vuepress/dist/dist.tar.gz"
          remote: "/data/wwwroot/www.losenone.cn"
          host: ${{secrets.PROD_HOST}}
          port: ${{secrets.PROD_PORT}}
          user: ${{secrets.PROD_USER}}
          key: ${{secrets.PROD_KEY}}
          pre_upload: cd /data/wwwroot/www.losenone.cn && rm -rf *
          post_upload: cd /data/wwwroot/www.losenone.cn && tar -xzvf dist.tar.gz && rm -f dist.tar.gz
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v -r
